version: "3"
services:
    db:
        image: mysql:latest
        ports:
            - 3306:3306
        #Habililta autenticaci칩n con contrase침a desde mysql
        command: --default-authentication-plugin=mysql_native_password
        #Variables de entorno
        environment:
            MYSQL_DATABASE: ae1_despliegue
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            #sincronizaci칩n bbdd
            - ./db/:/docker-entrypoint-initdb.d
        networks:
            - default
    www:
        build: ./php/
        ports:
            - 80:80
        volumes:
            - .:/var/www/html/
        #link con el contenedor de la bbdd
        links:
            - db
        #red de conexi칩n de los contenedores
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin
        #link con el contenedor de la bbdd
        links:
            - db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
